apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretname }}
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME:  {{ .Values.mongodbRootUsername | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodbRootPassword | quote }}