apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodeport.name }}
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30001
      

